### ISSUE TITLE
FlickrShow Adobe Flash widget no longer supported

### ISSUE THREAD

**Issue by smgriffin2** [micro-manager/micro-manager.org#37]
FlickrShow.md AdobeFlash format no longer supported.

Flash video inserted via FlickrShow include.

Tried to download, view, make a screencast but no luck viewing with adobe acrobat.

Other flash uses search: `include \#widget:Iframe`

**Comment by marktsuchida** [comment]
The FlickrShow page is not working even with MediaWiki currently. This page used to be linked from the page Gallery, but was unlinked in 2011, with no page linking to it since. So I'll remove it.

The Gallery page, in turn, is also broken on MediaWiki but the link it contains "works" in Jekyll. However, no page links to this page either, so it can be retired. (Last change in 2012).

It looks like this was a photo slideshow showing the Micro-Manager booth at ASCB 2011, created by Ziah Dean back in 2011 and initially hosted on Flickr. See `_pages/Micro-Manager_at_the_ASCB_Meeting_2011.md`, which still has a (nonfunctional) link to the slideshow hosted on `valelab.ucsf.edu` (now `valelab4.ucsf.edu`).

@nicost Are the photos hosted at https://valelab4.ucsf.edu/~MM/flashgallery/flashgallery2/flashgallery.html in a format that we can use (i.e. not just Flash)? If so, let me know how to access them and I'll see if they can be resurrected on the ASCB2011 page.

**Comment by smgriffin2** [comment]
If the slides can be recovered and we want to keep them available, I would be happy to convert to them to screencasts -- would need to figure out where to host (youtube,etc).
